### PR TITLE
Duplicate post xb integration

### LINKED ISSUE #67: Duplicate Post supports cloning Altis Experience Blocks
In our internal Post Cloner plugin, we needed to account for the analytics data that was being copied when posts were cloned. We need to reproduce this behavior with the Duplicate Post plugin. Notably, we need to ensure that analytics data is not overwritten when posts are forked and re-merged and that the analytics data is not copied into cloned posts.

We also need to remove this code and potentially move it into the Workflow module.

**Dev notes**
Original code in Altis Analytics:

```php
// Post cloner integration.
add_filter( 'post_cloner_meta_patterns_to_remove', __NAMESPACE__ . '\\post_cloner_meta_patterns_to_remove' );
add_filter( 'post_cloner_duplicate_post', __NAMESPACE__ . '\\post_cloner_update_xb_client_ids' );

/**
 * Meta patterns to avoid cloning.
 *
 * @param array $patterns Array of regex patterns to ignore.
 * @return array
 */
function post_cloner_meta_patterns_to_remove( array $patterns ) : array {
	// Ignore AB test data.
	$patterns[] = '/^_altis_ab_test_.*/';
	return $patterns;
}

/**
 * Update XB client IDs when cloning a post.
 *
 * @param array $post The duplicated post data.
 * @return array
 */
function post_cloner_update_xb_client_ids( array $post ): array {
	$post['post_content'] = preg_replace_callback(
		'#<!-- wp:altis/(personalization|experiment)\s+{.*?"clientId":"([a-z0-9-]+)"#',
		function ( array $matches ) : string {
			return str_replace( $matches[2], wp_generate_uuid4(), $matches[0] );
		},
		$post['post_content']
	);

	return $post;
}
```

Duplicate Post has equivalent hooks for both of these filters. These should be `duplicate_post_excludelist_filter` and `duplicate_post_new_post`. Both of these are documented in our documentation.

### PR DESCRIPTION
**Pull request by jazzsequence**
fixes #67 

This PR adds two Duplicate Post filters that perform the same duties as the Post Cloner filters in the Analytics module.

This also updates the Duplicate Post documentation for the meta key exclusion filter which actually takes wildcards, making the regex matching used in the Post Cloner filter unnecessary (but this isn't documented in the dev docs for Duplicate Posts).

* [x] remove the filters from Analytics. https://github.com/humanmade/altis-analytics/pull/154

### CODE REVIEW

**Review by roborourke — COMMENTED** [review]
Ha, nice. I somehow expected that to be super complicated.

Just realised why I thought it might be super complicated - are we able to tell if a post is a rewrite & republish vs a clone/copy? We would only want to update the XB client ID for a clone/copy I think. Otherwise we'll be getting a new XB on republish which probably wouldn't be expected behaviour.

**Comment by jazzsequence** [comment]
That's a good point. I'll need to dig into the internals to see if there's a specific difference. I know a lot of the functional stuff is the same but I assume there has to be something different (different meta key or something) that triggers the different behavior.

**Comment by jazzsequence** [comment]
Aha! Found it! 🎉

So it looks like 
* a) there's a completely separate method to handle copying a post for "Rewrite & Republish". This function wraps around the `create_duplicate` method. 
* b) There is no place to hook in (within Duplicate Post) _before_ the duplicate is created. There's the normal WP actions that could be hooked into presumably, but the post meta -- which is where it's defined if a post is rewritten or not -- isn't added until after the duplicate is created.

Thinking this through a bit, it doesn't matter so much if the client ID is changed on the _rewritten_ post, so long as it's the right/the same client ID when the copy is _republished_. My thought is that we could do a `preg_match` using the same pattern we're already using for the `str_replace` to pull out the original client ID when the post is being copied. And then when you go to _republish_ the post, we copy the stored client ID _back_ into the personalization block, so the ID that's in use doesn't actually change.

**Comment by roborourke** [comment]
The block client ID isn't stored in post meta anywhere, it's just part of the content so it's not that easy. A post might have multiple XBs so it'd be hard to know which ones to replace and to what.

I still think this needs a way to leave the XB client IDs intact still and probably needs to prevent the XB -> post creation / update logic when creating a rewrite & republish copy so that the XB is still associated with the published post.

Maybe we can contribute the necessary hooks needed upstream?

**Comment by jazzsequence** [comment]
I thought about contributing upstream. But I'm not sure the best place to hook in. When we'd need it is likely before it's reasonable to expect it (e.g. the post meta distinguishing a post as cloned or rewritten doesn't exist yet). 

I think on reflection, the simplest and most straightforward way to handle it is to not use their hooks at all and use WordPress' own `wp_insert_post` hook -- the very last thing before the post is published/updated. Wait until the end, when we would have all the post meta from Duplicate Post to tell us what type of post it is, and _at that point_ we replace the client ID if we need to. That way, we're only doing one thing and it's specifically targeted to the thing we want.

**Comment by roborourke** [comment]
Ah I see. So you could unhook this on an earlier priority if the rewrite & republish post meta is there too https://github.com/humanmade/aws-analytics/tree/master/inc/blocks/namespace.php#L33

**Comment by jazzsequence** [comment]
Yeah, I think that's where I'm leaning, just need to make sure I don't head into an issue where the client ID gets updated on every save.

**Comment by jazzsequence** [comment]
In retrospect, I think adding a hook upstream might make this a lot easier.

**Comment by jazzsequence** [comment]
Re-finagled the logic a bit. The details of what's happening is in the commit notes [here](https://github.com/humanmade/altis-workflow/pull/70/commits/a6021a8aeaf9228d5a4027f7887cbc3105f2c21c) but I'll summarize:

1. I'm hooking into a different action. This one fires after a new post is created and passes the new post ID and the original post object into it.
2. I added a bunch of checks to make sure we're _only_ looking at a cloned post and not a rewritten post. tl:dr; rewritten posts have _two_ specific meta keys we're looking for. All cloned posts have one of those. So we check to see if it's cloned _at all_ (and if not, bail) then we check to see if it's rewritten (and if so, bail). this ensures we're where we need to be. 
3. I'm also adding a new meta value. This meta value gets stored after we've updated the content to make sure we don't update it more than once. So we check to see if the meta value exists first, if not, update the content and store the meta key.
4. We're _excluding_ the new meta key from new duplicate posts, so if a duplicate of a duplicate is created, the client id's will be created fresh for those as well.

I _think_ this covers everything and it seems to be working on a bunch of tests, but I haven't tested some edge cases yet (like duplicates of duplicates) so I will do that tomorrow.

**Comment by roborourke** [comment]
Thanks @jazzsequence. Pretty gnarly problem, the post creation / save hooks are some of the hardest to work with. Kinda wish `add_action_once()` was a things sometimes.

Only other question I have is what happens to an existing XB shadow post's parent ID when a page is rewritten & republished. We need them to remain associated with the live / published post. The relevant logic from the analytics plugin is here https://github.com/humanmade/aws-analytics/blob/master/inc/blocks/namespace.php#L67

**Comment by jazzsequence** [comment]
The XB post parent wouldn't be affected. It would stay the same as before because we aren't doing anything to that post type (none of this stuff even triggers unless the shadow post was cloned -- and that assumes it was possible to clone those, which it isn't). When the rewritten post is republished, it inserts all the updates from the rewritten post back into the original post and deletes the copy* (and then adds a revision to the revision history), so the XB parent post ID won't change.

(* - I will doublecheck that this is, in fact accurate, but I'm 90% sure that the plugin keeps and republishes the original rather than replacing it with the rewritten copy.)

**Comment by jazzsequence** [comment]
**Update:** I've done some testing and I've confirmed some behavior.

* Cloned posts always get new client IDs. Clones of clones (and clones of clones of clones, etc) included.
* Rewritten posts retain their client IDs, including the duplicate copy of the post being rewritten.
* When a post is rewritten, the content of the duplicate post is inserted into the original post, so any references to that post/post ID are still valid (so XB "children" aren't orphaned because their parent is deleted).

This should be g2g and ready for another pass. 🙄

**Comment by jazzsequence** [comment]
@roborourke I added a new filter to the save post hook in AWS Analytics to allow a plugin to bail early from the sync to the XB shadow post. We use that here to check if the post being saved is a rewritten post and if so, we can exit out of the `save_post` actions. 

This does not affect when a rewritten post is being republished -- the republished post will carry with it any updates to the XB and the shadow post when it's copied back into the original.

**Review by roborourke — APPROVED** [review]

**Pull request merged**
